### PR TITLE
Added / Fixed versioning commands

### LINKED ISSUE #116: []version-Command to check if there is a new version on the remote

### PR DESCRIPTION
**Pull request by CodeMyst**
Closes #116

### CODE REVIEW

File: Commands/VersioningCommand.cs [hunk 1]
```diff
@@ -66,27 +62,61 @@ public async Task Update()
...
+                var cmd = RunShellScript("shell/update", true, pid);
+                cmd.WaitForExit ();
+                Log.WriteLine (cmd.StandardOutput.ReadToEnd ());
+
+                await ReplyAsync ("Restarting the bot... :arrows_counterclockwise: ");
+                Log.WriteLine ("Restarting the bot...");
+
+                // Create a file that will be checked on startup to check if the bot updated
+                // The channel ID is used so the bot knows where to send the updated message on startup
+                await File.WriteAllTextAsync (Path.Combine (Directory.GetCurrentDirectory (), "updated.txt"), Context.Guild.Id + "\n" + Context.Channel.Id);
```
Comment (YilianSource) [inline Commands/VersioningCommand.cs]: Really smart!
